# Generated by Django 2.2.6 on 2019-11-30 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_delivered',
            new_name='date_scheduled',
        ),
        migrations.AddField(
            model_name='product',
            name='approximate_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 11, 30, 19, 34, 54, 773421, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='scheduled',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes'), ('2', 'Pending')], default='2', max_length=2),
        ),
    ]
