# Generated by Django 2.2.6 on 2019-11-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20191130_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_scheduled',
            field=models.DateField(null=True),
        ),
    ]
