# Generated by Django 2.2.6 on 2019-11-30 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_auto_20191130_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Factory'),
        ),
    ]
