# Generated by Django 2.2.6 on 2019-12-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_auto_20191130_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collected',
            field=models.CharField(choices=[('0', 'No'), ('1', 'Yes')], default='0', max_length=2),
        ),
    ]
