# Generated by Django 2.2.6 on 2019-12-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='farmer',
        ),
    ]
