# Generated by Django 2.2.6 on 2019-12-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_auto_20191203_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='farmer',
            new_name='product',
        ),
    ]
