# Generated by Django 2.2.6 on 2019-11-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='userlevel',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('accounts', 'Accountant'), ('factory_admin', 'Factory Admin'), ('overadmin', 'Super Admin')], default='farmer', max_length=50, null=True),
        ),
    ]
