# Generated by Django 2.2.6 on 2019-11-27 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_factorystaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorystaff',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
