# Generated by Django 2.2.6 on 2019-11-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_factoryprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryprice',
            name='previous_price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
