# Generated by Django 2.2.6 on 2019-12-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_factoryprice_previous_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
